# Generated by Django 5.2.4 on 2026-09-04 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DislikedSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default='unknown', max_length=200)),
                ('artist_name', models.CharField(default='unknown', max_length=200)),
                ('track_name', models.CharField(default='unknown', max_length=200)),
                ('popularity', models.CharField(default='unknown', max_length=200)),
                ('year', models.CharField(default='unknown', max_length=200)),
                ('genre', models.CharField(default='unknown', max_length=200)),
                ('danceability', models.CharField(default='unknown', max_length=200)),
                ('energy', models.CharField(default='unknown', max_length=200)),
                ('loudness', models.CharField(default='unknown', max_length=200)),
                ('speechiness', models.CharField(default='unknown', max_length=200)),
                ('acousticness', models.CharField(default='unknown', max_length=200)),
                ('instrumentalness', models.CharField(default='unknown', max_length=200)),
                ('liveness', models.CharField(default='unknown', max_length=200)),
                ('valence', models.CharField(default='unknown', max_length=200)),
                ('tempo', models.CharField(default='unknown', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default='unknown', max_length=200)),
                ('artist_name', models.CharField(default='unknown', max_length=200)),
                ('track_name', models.CharField(default='unknown', max_length=200)),
                ('popularity', models.CharField(default='unknown', max_length=200)),
                ('year', models.CharField(default='unknown', max_length=200)),
                ('genre', models.CharField(default='unknown', max_length=200)),
                ('danceability', models.CharField(default='unknown', max_length=200)),
                ('energy', models.CharField(default='unknown', max_length=200)),
                ('loudness', models.CharField(default='unknown', max_length=200)),
                ('speechiness', models.CharField(default='unknown', max_length=200)),
                ('acousticness', models.CharField(default='unknown', max_length=200)),
                ('instrumentalness', models.CharField(default='unknown', max_length=200)),
                ('liveness', models.CharField(default='unknown', max_length=200)),
                ('valence', models.CharField(default='unknown', max_length=200)),
                ('tempo', models.CharField(default='unknown', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
