# Generated by Django 5.2.4 on 2026-09-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liked_songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritesong',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
